# Build the project

name: Build

env:
  PKG_VERSION: "8.0.0"
  BUILD_CONFIG: "Release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  # get nuget
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    # setup msbuild 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
       
    # restore packages
    - name: nuget restore
      run: nuget restore
    
    # build project 
    - name: Build with MSBuild
      run: msbuild Our.Umbraco.SilentUpgrade.sln -p:Configuration=${{ env.BUILD_CONFIG }} 
